### ISSUE TITLE
Tracking progress

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/chatgpt-clone#1]
High priority

- [x] Get backend working
- [x] Get frontend working
- [x] Integrate them
- [x] Documentation
- [x] QA integration (linting and formatting)
- [x] Containerization

Medium priority

- [x] Add unit tests to backend
- [x] Add unit tests to frontend

Low priority

- [x] Add logging
- [x] CI/CD
- [ ] precommit
- [x] accessibility 
- [ ] type coverage 
- [x] add load testing
- [ ] graceful handling of exceptions
- [ ] reorganization of the frontend directory
